{% set version = "v0.2.3" %}
{% set sha256 = "35e708df1fa5656a12a9960c3314615cd5ab748f16f07075f5af6539a6044265" %}

package:
  name: 'centreseq'
  version: '{{ version }}'

source:
  url: https://github.com/bfssi-forest-dussault/centreseq/archive/{{ version }}.zip 
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - cyvcf2
    - mmseqs2
    - prokka
    - muscle
    - seqkit
    - snp-sites

test:
  commands:
    - centreseq --version

about:
  home: https://github.com/bfssi-forest-dussault/centreseq
  license: MIT
  license_family: MIT
  summary: Fast generation of a core genome among bacterial strains
  dev_url: https://github.com/bfssi-forest-dussault/centreseq

extra:
  recipe-maintainers: bfssi-forest-dussault
