{% set name = "proteinortho" %}
{% set version = "6.0.2" %}
{% set sha256 = "36127c87cdef99bd4b9a80d06cb220d734f131a4d3434ab5ba7933b2613b5123" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/paulklemm_PHD/proteinortho/-/archive/v{{ version }}/proteinortho-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - openmp
    - openblas
  run:
    - perl
    - python
    - diamond
    - openmp
    - openblas
 
test:
  commands:
    - proteinortho --version
    - proteinortho_clustering -test

about:
  home: https://gitlab.com/paulklemm_PHD/proteinortho/
  license: GNU GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: "Proteinortho is a tool to detect orthologous genes within different species."
